# Generated by Django 4.1.1 on 2022-09-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itunes_id", models.BigIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                ("country_code", models.CharField(max_length=2)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
